### ISSUE TITLE
When the cursor is still in the URL box, hyperlink is not copied

### ISSUE THREAD

**Issue by ravigummadi** [dhruvtv/copylinkaddress#1]
## Steps to reproduce
- Go to the site: http://answers.microsoft.com/en-us
- After the page is loaded, click on the URL box and make sure that cursor is at the end of the URL
- Go to any of the links and do (Cmd + C)
- The link is not copied.

**Comment by dhruvtv** [comment]
Took so long and I still don't have a solution :)

The way the extension works is, once you hover a link:
If something is already selected in the page, it does nothing. Else, it takes the URL of the link you are hovering, copies it to an invisible span, programmatically selects the span. Now when you hits Cmd-C (Ctrl-C), the hidden selection is copied to clipboard.

If, at the time of hovering a link, the cursor was in a textbox (without anything selected), it is technically a zero-length selection in Chrome. So, the extension goes ahead and clears that selection (thereby taking the cursor away from the textbox!)

This works for all textboxes _in a page_. However, Google Chrome does not consider the omnibox as belonging to the page, and provides **NO OPTION** to programmatically take the focus/cursor away from the omnibox (vital for our extension). 

The issue is documented here : http://support.agilebits.com/discussions/1password-38-for-mac-from-agilebits-website/23119-cursor-focus-problem-with-chrome-extension. Search for "Chrome does not allow anything to take the focus away from the omnibox" in the page.

I'll update this space as soon as Chrome permits us to.
